# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grocery_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_text', models.CharField(max_length=200)),
                ('numofIngredient', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Grocery_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='grocery_item',
            name='grocery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shopping_List.Grocery_list'),
        ),
    ]
