# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 04:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shopping_List', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(default='Enter Recipe Name', max_length=50)),
                ('ingredients', models.TextField(default='')),
                ('notes', models.TextField(default='')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recipe_name'],
            },
        ),
        migrations.RemoveField(
            model_name='grocery_item',
            name='grocery',
        ),
        migrations.RemoveField(
            model_name='grocery_list',
            name='grocery_text',
        ),
        migrations.AddField(
            model_name='grocery_list',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='grocery_list',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grocery_list',
            name='text',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='grocery_list',
            name='title',
            field=models.CharField(default='Enter Title', max_length=140),
        ),
        migrations.DeleteModel(
            name='grocery_item',
        ),
    ]
