# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 03:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shopping_List', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_amt', models.FloatField(choices=[('.125', '1/8'), ('.25', '1/4'), ('.5', '1/2'), ('.75', '3/4'), ('1.00', '1'), ('1.25', '1 1/4'), ('1.50', '1 1/2'), ('1.75', '1 3/4'), ('2', '2'), ('2.25', '2 1/4'), ('2.50', '2 1/2'), ('2.75', '2 3/4'), ('3.00', '3'), ('4.00', '4'), ('5.00', '5'), ('6.00', '6'), ('7.00', '7'), ('8.00', '8'), ('9.00', '9'), ('10.00', '10')], default=0, max_length=5)),
                ('ingredient_meas', models.CharField(choices=[('t', 'Teaspoon'), ('T', 'Tablespoon'), ('cup', 'Cup'), ('piece', 'Piece(s)')], default='', max_length=5)),
                ('ingredient_name', models.TextField(default='Hello Notes', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(default='Test', max_length=50)),
                ('notes', models.TextField()),
                ('ingredients', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Shopping_List.Ingredients')),
            ],
            options={
                'ordering': ['recipe_name'],
            },
        ),
        migrations.RemoveField(
            model_name='grocery_item',
            name='grocery',
        ),
        migrations.RemoveField(
            model_name='grocery_list',
            name='grocery_text',
        ),
        migrations.AddField(
            model_name='grocery_list',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='grocery_list',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grocery_list',
            name='text',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='grocery_list',
            name='title',
            field=models.CharField(default='AAA', max_length=140),
        ),
        migrations.DeleteModel(
            name='grocery_item',
        ),
    ]
