# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 23:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shopping_List', '0002_auto_20171204_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default='Enter Recipe Name', max_length=50),
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
