# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_List', '0002_auto_20171120_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='DEFAULT VALUE', max_length=140)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
