# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_List', '0002_auto_20171202_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='notes',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='recipe',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='Shopping_List.Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient_name',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='notes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shopping_List.Recipe'),
        ),
    ]
