# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_List', '0003_grocery_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient_meas',
            field=models.CharField(choices=[('t', 'Teaspoon'), ('T', 'Tablespoon'), ('cup', 'Cup'), ('piece', 'Piece(s)'), ('', 'None')], max_length=5),
        ),
    ]
