# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_List', '0004_auto_20171127_1713'),
        ('Shopping_List', '0004_auto_20171126_1110'),
    ]

    operations = [
    ]
