# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_List', '0006_auto_20171129_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['recipe_name']},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_amt',
            field=models.FloatField(choices=[('.125', '1/8'), ('.25', '1/4'), ('.5', '1/2'), ('.75', '3/4'), ('1.00', '1'), ('1.25', '1 1/4'), ('1.50', '1 1/2'), ('1.75', '1 3/4'), ('2', '2'), ('2.25', '2 1/4'), ('2.50', '2 1/2'), ('2.75', '2 3/4'), ('3.00', '3'), ('4.00', '4'), ('5.00', '5'), ('6.00', '6'), ('7.00', '7'), ('8.00', '8'), ('9.00', '9'), ('10.00', '10')], default=0, max_length=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_meas',
            field=models.CharField(choices=[('t', 'Teaspoon'), ('T', 'Tablespoon'), ('cup', 'Cup'), ('piece', 'Piece(s)')], default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_name',
            field=models.TextField(default='Hello Notes', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(default='Shrimp Scampi', max_length=50),
        ),
    ]
