# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 01:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shopping_List', '0007_auto_20171201_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery_list',
            name='owner',
            field=models.ForeignKey(default=-1.0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredient_amt',
            field=models.FloatField(choices=[('.125', '1/8'), ('.25', '1/4'), ('.5', '1/2'), ('.75', '3/4'), ('1.00', '1'), ('1.25', '1 1/4'), ('1.50', '1 1/2'), ('1.75', '1 3/4'), ('2', '2'), ('2.25', '2 1/4'), ('2.50', '2 1/2'), ('2.75', '2 3/4'), ('3.00', '3'), ('4.00', '4'), ('5.00', '5'), ('6.00', '6'), ('7.00', '7'), ('8.00', '8'), ('9.00', '9'), ('10.00', '10'), ('11.00', '11')], default=0, max_length=5),
        ),
    ]
