# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_List', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_amt', models.FloatField(choices=[('.125', '1/8'), ('.25', '1/4'), ('.5', '1/2'), ('.75', '3/4'), ('1.00', '1'), ('1.25', '1 1/4'), ('1.50', '1 1/2'), ('1.75', '1 3/4'), ('2', '2'), ('2.25', '2 1/4'), ('2.50', '2 1/2'), ('2.75', '2 3/4'), ('3.00', '3'), ('4.00', '4'), ('5.00', '5'), ('6.00', '6'), ('7.00', '7'), ('8.00', '8'), ('9.00', '9'), ('10.00', '10')], max_length=5)),
                ('ingredient_meas', models.CharField(choices=[('t', 'Teaspoon'), ('T', 'Tablespoon'), ('cup', 'Cup'), ('piece', 'Piece(s)')], max_length=5)),
                ('ingredient_name', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='grocery_item',
            name='grocery',
        ),
        migrations.DeleteModel(
            name='grocery_item',
        ),
        migrations.DeleteModel(
            name='Grocery_list',
        ),
    ]
