# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping_List', '0003_grocery_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery_list',
            name='title',
            field=models.CharField(max_length=140),
        ),
    ]
